// Fail ini dijana OTOMATIK oleh dashboard — jangan edit tangan.
const produk = [
  { nama:"Shaker Bar 350ml", cat:"bawah2", harga:1.53, tier:"RM1.53/104PCS • RM1.50/500PCS •  RM1.40/5,000PCS", cover:"images/covers/WhatsApp-Image-2026-07-11-at-9.26.18-PM-1.webp", asal:"images/IMG_3560.HEIC.jpg", desc:"Sport Shaker - BPA Free \nTahan Panas\nSesuai untuk FREE GIFT product\n5 colors\n1 side printing\n1 color printing\nQuality - Anti leak\nReady stock" },
  { nama:"Snap Lid Bottles", cat:"bawah4", harga:3.0, tier:"RM3.4/500pcs • RM3.2/1000pcs • RM3.0/3000pcs", cover:"images/covers/snap-lid.webp", asal:"images/9ef9R5bb4mh9RKIRhGYLqGVi1vdsBJvMWNuaQwIC.webp", desc:"Snap Lid Bottles - Come with Snap Lid Cover - Descriptions Snap Lid BottlesSKU : RM405400mlCome with grey strapMaterial : Wheat StrawFood grade PlasticSilicone ring to prevent water leak4 colors1 side printing1 color logo printingQuality - Anti leak100pcs/ctnReady stock" },
  { nama:"Elegant Tumbler", cat:"bawah4", harga:3.2, tier:"RM3.5/500pcs • RM3.3/1000pcs • RM3.2/3000pcs", cover:"images/covers/elegant-tumbler.webp", asal:"images/qcY0xfyG8CkCuXHxe9HHEcFuxUoYGlHxa9cEIDbO.webp", desc:"Elegant Tumbler - Tumbler with elegant curve - Descriptions Elegant TumblerSKU : RM404400mlCome with grey strapMaterial : Wheat StrawFood grade PlasticSilicone ring to prevent water leak4 colors1 side printing1 color logo printingQuality - Anti leak100pcs/ctnReady stock" },
  { nama:"Sport Shaker", cat:"bawah4", harga:3.1, tier:"RM3.5/500pcs • RM3.3/1000pcs • RM3.1/3000pcs", cover:"images/covers/sport-shaker.webp", asal:"images/lYPtSu926Sp4kYv7kRZg24fXxHsm5YTpuMjn3koO.webp", desc:"Sport Shaker - BPA Free Sport Shaker with FREE Shaker Ball - Descriptions SKU : RM403400mlSize 16cm x 7cmCome with grey strapMaterial : PP Food grade plasticAnti leaksFREE STAINLESS STEEL SHAKER BALL5 colors1 side printing1 color printingQuality - Anti leakReady stock" },
  { nama:"Solid Plastic Cup", cat:"bawah2", harga:1.6, tier:"RM1.80/500pcs • RM1.70/1000pcs • RM1.60/3000pcs", cover:"images/covers/solid-cup.webp", asal:"images/gsM2OMtBUZppvtFbSkKNGuwJRYKHPydNi9wEZ2FE.webp", desc:"Solid Plastic Cup - Plastics Drink Bottles with anti leak feature - Solid Plastic CupSKU : RM203450mlCome with grey strapMaterial : Wheat StrawFood grade PlasticSilicone ring to prevent water leak4 colors1-2 side printingQuality - Anti leak200pcs/ctnReady stock" },
  { nama:"Star Mini Plastic Cup", cat:"bawah2", harga:1.6, tier:"RM1.80/500pcs • RM1.70/1000pcs • RM1.60/3000pcs", cover:"images/covers/star-mini.webp", asal:"images/oTFhLG2zaozg6O5p8zKGulb5Dip8D3TNjQ2zMNRf.webp", desc:"Star Mini Plastic Cup - Mini Plastic Cup with Anti leak feature - Star Mini Plastic Cup RM202 Price RM1.80 - 500pcs RM1.70 - 1000pcs RM1.60 - 3000pcs above 350ml Come with grey strap Material : PP Plastic Food grade PlasticRubber silicone to prevent leaking 11 colors 1-2 side printing Quality - Anti leak 200pcs/ctn Ready stockDirect from China Factory via sea shipment" },
  { nama:"Colorful Plastic Cup", cat:"bawah2", harga:0.9, tier:"", cover:"images/covers/colorful-cup.webp", asal:"images/fl50YsNtrRp32fQkDJm6gs19uOis3UkcHqxMUaT9.webp", desc:"Colorful Plastic Cup - Low cost Plastic Drink Cup - Colorful Plastic Cup Code : RM201 MOQ 1000 Price : RM1.40 (500) RM1.10 (1000)RM0.90 (5000) 380ml 5 colors 1-2 side printing Quality - Average 500pcs/ctn Ready stock" },
  { nama:"Glossy Mini Plastic Bottles", cat:"bawah2", harga:1.6, tier:"RM1.80/500pcs • RM1.70/1000pcs • RM1.60/3000pcs", cover:"images/covers/glossy-mini.webp", asal:"images/lNwXeM12frOokCTgL2pLWxRlLLcwD0Pp34lUs94c.webp", desc:"Glossy Mini Plastic Bottles - Mini Glossy Surface Drink Bottles with anti leak feature - Glossy Plastic Drink BottlesSKU : RM205350mlCome with grey strapMaterial : PP plasticFood grade PlasticCome with silicone ring to prevent water leak4 colors1-2 side printingQuality - Anti leak400pcs/ctnETA 30-35 days" },
  { nama:"Transparent Plastic Bottles", cat:"bawah2", harga:1.6, tier:"RM1.80/500pcs • RM1.70/1000pcs • RM1.60/3000pcs", cover:"images/covers/transparent.webp", asal:"images/peXeKK9s65BMNMCexKSuwkfdAd46JdgKEwlfa9gf.webp", desc:"Transparent Plastic Bottles - Plastic Drink Bottles with anti leak feature - Transparent Plastic CupSKU : RM204450mlCome with grey strapMaterial : PP plasticFood grade PlasticSilicone rubber to prevent water leak4 colors1-2 side printingQuality - Anti leak200pcs/ctnReady stock" },
  { nama:"Plastic Drink Bottles With Clip Lids", cat:"bawah2", harga:1.3, tier:"RM1.50/500pcs • RM1.40/1000pcs • RM1.30/3000pcs", cover:"images/covers/clip-lids.webp", asal:"images/mDY8V2NR9ZXZSP37CH0ffkuBgsR9qZoyAZ2bZf0X.webp", desc:"Plastic Drink Bottles With Clip Lids - Plastic Bottles with Multiple color Clip Lid - Plastic Drink Bottle with Clip LidRM206350mlCome with grey strapMaterial : PP plasticFood grade Plastic4 colors Lids1-2 side printingQuality : Average- Anti leakCome with rubber ring to prevent water leaks 400pcs/ctnReady stock" },
  { nama:"Double Cup Drink Bottles", cat:"bawah4", harga:2.69, tier:"RM2.89/500pcs • RM2.79/1000pcs • RM2.69/3000pcs", cover:"images/covers/double-cup.webp", asal:"images/PBjB4I6Lb0k1Kd0bzv3VLAd5jhOcJCrlPYciuiMO.webp", desc:"Double Cup Drink Bottles - Double Cup can withstand heat compared to ordinary bottles - Double Plastic BottlesRM401350mlCome with grey strapDouble cup featureCan withstand heat compared to ordinary bottlesMaterial : Wheat Straw environmental friendly materialFood grade Plastic4 colors1 side printingQuality : Anti leakCome with rubber ring to prevent water leak100pcs/ctnReady stock" },
  { nama:"Double Cup Bottles with handle", cat:"bawah4", harga:2.9, tier:"RM3.1/500pcs • RM3.0/1000pcs • RM2.90/3000pcs", cover:"images/covers/double-cup-handle.webp", asal:"images/CLRu2ISxwrqTwAREJ5SWPsmNKmSVZf5vWpboQtbs.webp", desc:"Double Cup Bottles with handle - Bottles that can withstand heat compared to other ordinary bottles - Double Plastic Bottles with HandleRM401350mlCome with grey strapWith handl easy to carryDouble cup featureCan withstand heat compared to ordinary bottlesMaterial : Wheat Straw environmental friendly materialFood grade Plastic4 colors1 side printingQuality : Anti leakCome with rubber ring to prevent water leak100pcs/ctnReady stock" },
];
const catLabel = { bawah2:"Bawah RM2", bawah4:"Bawah RM4" };
